# Minimal Mistakes Jekyll Theme Configuration

remote_theme: "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin: "dark" # Choose your skin: "air", "dark", "plum", etc.

# Site Settings
locale: "en-US"
title: "Elijah's Cybersecurity Portfolio"
title_separator: "-"
subtitle: "Exploring cybersecurity through hands-on labs and projects"
name: &name "Elijah"
description: &description "A portfolio showcasing cybersecurity labs, phishing analysis, malware forensics, and network security projects."
url: "https://ourworldofdreams.github.io/portfolio" # Replace with your GitHub Pages URL
baseurl: "" # Leave blank unless you need a subpath like "/blog"
repository: "ourworldofdreams/portfolio" # Replace with your repository name
logo: "/assets/images/logo.png" # Path to a custom logo if you have one
masthead_title: "Elijah's Portfolio" # Optional masthead title
words_per_minute: 200

# SEO and Analytics
google_site_verification: "" # Optional for SEO
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-XXXXX-Y" # Replace with your Google Analytics ID

# Author Details
author:
  name: *name
  avatar: "/assets/images/elijah-avatar.jpg" # Replace with your profile photo
  bio: "Cybersecurity professional specializing in phishing analysis, malware forensics, and threat detection."
  location: "Southern U.S."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/darralynmiller23"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ourworldofdreams"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:elijah6023@gmail.com"

# Navigation
navigation:
  main:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "About"
      url: "/about/"
    - title: "Blog"
      url: "/blog/"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/darralynmiller23"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:elijah6023@gmail.com"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# Conversion Settings
permalink: /:categories/:title/
paginate: 5 # Number of posts per page
timezone: America/New_York # Update based on your location

# Collections (Optional)
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Compression
compress_html:
  clippings: all
