# Jekyll Site Deployment Workflow
name: Deploy Jekyll Site to Pages

on:
  # Trigger this workflow on push to the default branch
  push:
    branches: ["main", "master"] # Ensure it works for both main and master branches
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04 # Use a stable runner version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify Ruby version
          bundler-cache: true
          
      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04 # Stable runner version
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        
